### PR TITLE
Fix Collector config

### PR DESCRIPTION
**Pull request by iNikem**

### CODE REVIEW

**Comment by laurit** [comment]
Profiling test also has collector conf that has the same issue. The bigger issue is what to do with windows, I believe it runs a different version of collector that probably does not accept the new style of conf.

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by laurit** [comment]
Upstream completely removed collector from smoke tests and sends data directly to fakebackend. I believe we should do the same to simplify things. For example the windows collector version we used was built by upstream and that also got removed.

**Comment by mateuszrzeszutek** [comment]
The agent exports metrics in the signalfx format, the fake backend can't accept them - we have to use the collector as a translation layer.

**Comment by iNikem** [comment]
Should we update https://github.com/signalfx/splunk-otel-java/pull/190 to contrib and use it?

**Comment by mateuszrzeszutek** [comment]
~~Is there a contrib windows image?~~ Looks like there's no contrib Windows image: https://github.com/open-telemetry/opentelemetry-collector/issues/2715 😢 
We'd have to build it ourselves

**Comment by iNikem** [comment]
> ~Is there a contrib windows image?~ Looks like there's no contrib Windows image: [open-telemetry/opentelemetry-collector#2715](https://github.com/open-telemetry/opentelemetry-collector/issues/2715) 😢
> We'd have to build it ourselves

@mateuszrzeszutek isn't your #190 exactly about that?

**Comment by mateuszrzeszutek** [comment]
Right... that's strange; I was almost certain that we're using splunk-otel-collector in linux tests and that's why I chose it for Windows too - but we're actually using contrib everywhere.
Anyway, I'll update that PR so that it builds a contrib-based image - let's use the same collector everywhere.

**Pull request merged**
