### PR TITLE
Scripts to build docker images for acceptance test matrix

### PR DESCRIPTION
**Pull request by iNikem**

### CODE REVIEW

**Review by jkwatson — APPROVED** [review]
Excellent. Do we think this is something we'll eventually contribute upstream?

**Comment by iNikem** [comment]
> Excellent. Do we think this is something we'll eventually contribute upstream?

Yes, we have such plans :)

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by vovencij** [comment]
Will the support for pushing images to some repo follow?

**Comment by iNikem** [comment]
> Will the support for pushing images to some repo follow?

Good point, let me investigate that...

**Comment by vovencij** [comment]
Also, why shell scripts? This will not scale for building Windows images and we will need those next. Using gradle, for example, would work nicely cross-platform.

**Comment by iNikem** [comment]
You cannot build both linux and windows images from the same dockerfiles, can you? How can this work "cross-platform"? Or what do I miss?

**Comment by vovencij** [comment]
My point is that you have a bunch of scripts, that replace variables in the templates. For windows, there will be just another set of templates and variables. So this replacement logic will have to be reimplemented from scratch (because shell script won't work in windows) and there will be 2 ways for doing almost the same thing.

**Comment by vovencij** [comment]
And then there will be 3rd place where similar logic will be duplicated - when test would want to use an image from the matrix. Super-ideally this image-name composition logic could be in just one place. But I don't know how to share this logic between build scripts and tests.

**Comment by iNikem** [comment]
@vovencij replaces shell scripts with gradle tasks. Image publishing still does not work as we don't have permissions to setup it

**Comment by vovencij** [comment]
Can you make `matrix` a proper sub-project with gradle tasks under there? As a next step I will add building of `app.war` in that same project.

**Comment by vovencij** [comment]
✅  I would now approve, if I had the right :)

**Pull request merged**
