### PR TITLE
Skip publishing splunk-otel-javaagent-all.jar

### PR DESCRIPTION
**Pull request by laurit**

### CODE REVIEW

**Review by breedx-splk — APPROVED** [review]
Weird, I thought we got rid of or stopped publishing that a long time ago...but maybe I'm thinking of upstream.

**Comment by breedx-splk** [comment]
Actually, we might have some internal uses that rely on that name. Let's chat offline.

**Comment by laurit** [comment]
> Weird, I thought we got rid of or stopped publishing that a long time ago...but maybe I'm thinking of upstream.

Yes upstream removed it a long time ago, we deprecated it in https://github.com/signalfx/splunk-otel-java/releases/tag/v1.8.0

**Comment by breedx-splk** [comment]
Cool, I think the other mitigations we have in place now should be enough. I'm ok with merging this. Thanks!

**Pull request merged**
