### PR TITLE
Gitlab releaser job

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**

### CODE REVIEW

**Review by iNikem — APPROVED** [review]

**Comment by iNikem** [comment]
@owais Please take a look as well

**Review by owais — COMMENTED** [review]
PR LGTM but the build failed in GitLab.

**Review by owais — APPROVED** [review]

**Comment by mateuszrzeszutek** [comment]
> PR LGTM but the build failed in GitLab.

Yeah, I'm running into a lot of problems with docker testcontainers in GitLab. I'll make this a draft PR, since this still needs more work.

**Comment by mateuszrzeszutek** [comment]
I ended up making the release process as simple as possible: just build the jar and calculate a checksum; tests will run on GH CI.

**Pull request merged**
