### PR TITLE
Rename middleware to webengine

### PR DESCRIPTION
**Pull request by iNikem**
Just search and replace, no other changes

/cc @theletterf The following documentation (and link to it) should be fixed as well:

https://docs.splunk.com/Observability/gdi/get-data-in/application/java/configuration/java-otel-metrics-attributes.html#middleware-attributes-java-otel

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]

**Review by breedx-splk — APPROVED** [review]
The motivation is unclear, but this seems fine to me.

**Comment by iNikem** [comment]
> The motivation is unclear, but this seems fine to me.

`middleware` was our invention before spec got `webengine`. So this PR now starts using the official semantic attribute for this information.

**Comment by theletterf** [comment]
Currently OoO — please report this and other changes through our Docs Jira. Thanks!

**Pull request merged**
