### PR TITLE
introduce MetricsDependentInstrumentationModule

### PR DESCRIPTION
**Pull request by breedx-splk**
I'm torn -- on the one hand we keep seeing this pattern repeat itself and this is a cheesy way to button up some of that duplication...but on the other hand it makes me pretty uncomfortable to add another class to the inheritance tree.

Curious what others think. Good idea or just leave well enough alone?

### CODE REVIEW

**Comment by mateuszrzeszutek** [comment]
Hmm, we don't seem to save that much code on that.
Maybe, as an alternative, a `SplunkMetrics` class in `:bootstrap` with a single `static boolean enabled()` method would work?

**Comment by breedx-splk** [comment]
> Hmm, we don't seem to save that much code on that. Maybe, as an alternative, a `SplunkMetrics` class in `:bootstrap` with a single `static boolean enabled()` method would work?

Yeah, it's a bunch of boilerplate to still implement those methods tho, even if delegated. 🤷🏻

**Comment by mateuszrzeszutek** [comment]
True that. Okay, I don't have any better idea then - I'm fine with merging this PR, and I won't be sad if you decide to close it without merging.

**Comment by breedx-splk** [comment]
@laurit @iNikem @agoallikmaa @jkwatson any thoughts?

**Comment by jkwatson** [comment]
"prefer delegation to inheritance"?

**Comment by breedx-splk** [comment]
> "prefer delegation to inheritance"?

That would be an exciting change.  :)

**Comment by laurit** [comment]
I'd rename `MetricsDependentInstrumentationModule` -> `MetricsInstrumentationModule`, otherwise looks fine. It does remove a copy-pasted method and as it isn't a public api, we have all the options to change it in the future if we so desire. I think we can merge this.

**Review by mateuszrzeszutek — APPROVED** [review]

**Review by laurit — APPROVED** [review]

**Pull request merged**
